/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FlatListing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedAt' : IDL.Int,
  'contactName' : IDL.Text,
  'rentPrice' : IDL.Nat,
  'bedrooms' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'contactEmail' : IDL.Text,
  'bathrooms' : IDL.Nat,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
  'imageHashes' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MarkUnavailableInput = IDL.Record({
  'listingId' : IDL.Nat,
  'contactEmail' : IDL.Text,
});
export const FlatListingInput = IDL.Record({
  'title' : IDL.Text,
  'contactName' : IDL.Text,
  'rentPrice' : IDL.Nat,
  'bedrooms' : IDL.Nat,
  'description' : IDL.Text,
  'contactEmail' : IDL.Text,
  'bathrooms' : IDL.Nat,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
  'imageHashes' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'getAllListings' : IDL.Func([], [IDL.Vec(FlatListing)], ['query']),
  'getAvailableListings' : IDL.Func([], [IDL.Vec(FlatListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [FlatListing], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markListingUnavailable' : IDL.Func([MarkUnavailableInput], [], []),
  'postListing' : IDL.Func([FlatListingInput], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleListingAvailability' : IDL.Func([IDL.Nat], [], []),
  'updateListing' : IDL.Func([IDL.Nat, FlatListingInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FlatListing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedAt' : IDL.Int,
    'contactName' : IDL.Text,
    'rentPrice' : IDL.Nat,
    'bedrooms' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'contactEmail' : IDL.Text,
    'bathrooms' : IDL.Nat,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
    'imageHashes' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MarkUnavailableInput = IDL.Record({
    'listingId' : IDL.Nat,
    'contactEmail' : IDL.Text,
  });
  const FlatListingInput = IDL.Record({
    'title' : IDL.Text,
    'contactName' : IDL.Text,
    'rentPrice' : IDL.Nat,
    'bedrooms' : IDL.Nat,
    'description' : IDL.Text,
    'contactEmail' : IDL.Text,
    'bathrooms' : IDL.Nat,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
    'imageHashes' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'getAllListings' : IDL.Func([], [IDL.Vec(FlatListing)], ['query']),
    'getAvailableListings' : IDL.Func([], [IDL.Vec(FlatListing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [FlatListing], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markListingUnavailable' : IDL.Func([MarkUnavailableInput], [], []),
    'postListing' : IDL.Func([FlatListingInput], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleListingAvailability' : IDL.Func([IDL.Nat], [], []),
    'updateListing' : IDL.Func([IDL.Nat, FlatListingInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
