/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FlatListing {
  'id' : bigint,
  'title' : string,
  'postedAt' : bigint,
  'contactName' : string,
  'rentPrice' : bigint,
  'bedrooms' : bigint,
  'isAvailable' : boolean,
  'description' : string,
  'contactEmail' : string,
  'bathrooms' : bigint,
  'location' : string,
  'contactPhone' : string,
}
export interface FlatListingInput {
  'title' : string,
  'contactName' : string,
  'rentPrice' : bigint,
  'bedrooms' : bigint,
  'description' : string,
  'contactEmail' : string,
  'bathrooms' : bigint,
  'location' : string,
  'contactPhone' : string,
}
export interface MarkUnavailableInput {
  'listingId' : bigint,
  'contactEmail' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'getAvailableListings' : ActorMethod<[], Array<FlatListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[bigint], FlatListing>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markListingUnavailable' : ActorMethod<[MarkUnavailableInput], undefined>,
  'postListing' : ActorMethod<[FlatListingInput], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];